from pathlib import Path
lines = []
def A(s): lines.append(s)
A("<script setup lang=\"ts\">")
A("import { computed, onMounted, onBeforeUnmount, ref, watch } from 'vue'")
A("import { useRoute, useRouter } from 'vue-router'")
A("import { Empty, message } from 'ant-design-vue'")
A("import {")
A("  AppstoreOutlined,")
A("  BookOutlined,")
A("  BellOutlined,")
A("  FolderOpenOutlined,")
A("  MessageOutlined,")
A("  SearchOutlined,")
A("  ShopOutlined,")
A("  TeamOutlined,")
A("} from '@ant-design/icons-vue'")
A("import {")
A("  errorMessage,")
A("  fetchAds,")
A("  fetchBoards,")
A("  fetchNotices,")
A("  fetchPosts,")
A("  type AdSlot,")
A("  type Board,")
A("  type Notice,")
A("  type Post,")
A("} from '@/api'")
A("import PageContainer from '@/components/PageContainer.vue'")
A("import VerifiedBadge from '@/components/VerifiedBadge.vue'")
A("")
A("const route = useRoute()")
A("const router = useRouter()")
A("const boards = ref<Board[]>([])")
A("const posts = ref<Post[]>([])")
A("const ads = ref<AdSlot[]>([])")
A("const notices = ref<Notice[]>([])")
A("const loading = ref(true)")
A("const search = ref('')")
A("const adIndex = ref(0)")
A("const noticeOpen = ref(false)")
A("const simpleEmpty = Empty.PRESENTED_IMAGE_SIMPLE")
A("let timer: number | undefined")
A("")
A("const iconMap: Record<string, any> = {")
A("  message: MessageOutlined,")
A("  book: BookOutlined,")
A("  folder: FolderOpenOutlined,")
A("  team: TeamOutlined,")
A("  shop: ShopOutlined,")
A("}")
A("")
A("const activeBoard = computed(() => boards.value.find((item) => item.slug === String(route.params.slug || '')))")
A("const pageTitle = computed(() => activeBoard.value?.name || (route.params.slug ? '板块内容' : '社区首页'))")
A("const pageDescription = computed(() => activeBoard.value?.description || '讨论、攻略、资源与组队')")
A("const isHome = computed(() => !route.params.slug)")
A("const currentAd = computed(() => ads.value[adIndex.value] || null)")
A("const pinnedPosts = computed(() => posts.value.filter((x) => x.pinned))")
A("const normalPosts = computed(() => posts.value.filter((x) => !x.pinned))")
A("")
A("function startCarousel() {")
A("  stopCarousel()")
A("  if (ads.value.length <= 1) return")
A("  timer = window.setInterval(() => {")
A("    adIndex.value = (adIndex.value + 1) % ads.value.length")
A("  }, 4500)")
A("}")
A("function stopCarousel() {")
A("  if (timer) {")
A("    window.clearInterval(timer)")
A("    timer = undefined")
A("  }")
A("}")
A("")
A("async function load() {")
A("  loading.value = true")
A("  try {")
A("    const tasks: Promise<any>[] = [")
A("      fetchBoards().then((v) => { boards.value = v }),")
A("      fetchPosts({ board: String(route.params.slug || ''), q: search.value.trim() || undefined }).then((v) => { posts.value = v }),")
A("    ]")
A("    if (isHome.value) {")
A("      tasks.push(fetchAds().then((v) => { ads.value = v; adIndex.value = 0; startCarousel() }))")
A("      tasks.push(fetchNotices().then((v) => { notices.value = v }))")
A("    }")
A("    await Promise.all(tasks)")
A("  } catch (error) {")
A("    message.error(errorMessage(error, '社区内容加载失败'))")
A("  } finally {")
A("    loading.value = false")
A("  }")
A("}")
A("")
A("function submitSearch() { load() }")
A("function openAd(ad: AdSlot | null) {")
A("  if (ad?.link_url) window.open(ad.link_url, '_blank', 'noopener,noreferrer')")
A("}")
A("function formatDate(value: string) {")
A("  try {")
A("    return new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })")
A("  } catch { return value }")
A("}")
A("function excerpt(text: string) {")
A("  const clean = (text || '').replace(/\\s+/g, ' ').trim()")
A("  return clean.length > 120 ? clean.slice(0, 120) + '…' : clean")
A("}")
A("")
A("watch(() => route.params.slug, () => { search.value = ''; load() })")
A("onMounted(load)")
A("onBeforeUnmount(stopCarousel)")
A("</script>")
A("")
A("<template>")
A("  <PageContainer :title=\"pageTitle\" :description=\"pageDescription\">")
A("    <template #extra>")
A("      <a-space>")
A("        <a-badge v-if=\"isHome\" :count=\"notices.length\" :overflow-count=\"9\" :offset=\"[-2, 2]\">")
A("          <a-button @click=\"noticeOpen = true\"><BellOutlined /> 公告</a-button>")
A("        </a-badge>")
A("        <a-button type=\"primary\" @click=\"router.push('/posts/new')\">发布新帖</a-button>")
A("      </a-space>")
A("    </template>")
A("")
A("    <section v-if=\"isHome\" class=\"ad-banner-wrap\" aria-label=\"广告\">")
A("      <button")
A("        v-if=\"currentAd\"")
A("        type=\"button\"")
A("        class=\"ad-banner\"")
A("        @click=\"openAd(currentAd)\"")
A("        @mouseenter=\"stopCarousel\"")
A("        @mouseleave=\"startCarousel\"")
A("      >")
A("        <img v-if=\"currentAd.image_url\" :src=\"currentAd.image_url\" :alt=\"currentAd.title || '广告'\" class=\"ad-banner-img\" />")
A("        <div v-else class=\"ad-banner-fallback\">")
A("          <span class=\"ad-badge\">广告</span>")
A("          <strong>{{ currentAd.title || '社区广告位' }}</strong>")
A("          <span v-if=\"currentAd.link_url\" class=\"ad-hint\">点击了解详情</span>")
A("        </div>")
A("        <span v-if=\"currentAd.image_url\" class=\"ad-badge on-image\">广告</span>")
A("      </button>")
A("      <div v-else class=\"ad-banner empty-banner\">")
A("        <span class=\"ad-badge\">广告</span>")
A("        <span>暂无广告，可在后台「广告管理」配置轮播</span>")
A("      </div>")
A("      <div v-if=\"ads.length > 1\" class=\"ad-dots\">")
A("        <button")
A("          v-for=\"(item, idx) in ads\"")
A("          :key=\"item.id\"")
A("          type=\"button\"")
A("          class=\"ad-dot\"")
A("          :class=\"{ active: idx === adIndex }\"")
A("          @click=\"adIndex = idx; startCarousel()\"")
A("        />")
A("      </div>")
A("    </section>")
A("")
A("    <section class=\"search-section\">")
A("      <a-input-search")
A("        v-model:value=\"search\"")
A("        size=\"large\"")
A("        allow-clear")
A("        enter-button=\"搜索\"")
A("        :placeholder=\"isHome ? '搜索帖子、攻略、资源…' : ('在「' + pageTitle + '」中搜索')\"")
A("        @search=\"submitSearch\"")
A("      >")
A("        <template #prefix><SearchOutlined class=\"search-icon\" /></template>")
A("      </a-input-search>")
A("    </section>")
A("")
A("    <div class=\"content-grid home-body\">")
A("      <main>")
A("        <div v-if=\"pinnedPosts.length\" class=\"pinned-block\">")
A("          <div class=\"feed-toolbar\"><div class=\"feed-title\"><h2>置顶帖子</h2></div></div>")
A("          <div class=\"feed-list pro-card pinned-list\">")
A("            <RouterLink v-for=\"post in pinnedPosts\" :key=\"'p'+post.id\" :to=\"`/posts/${post.id}`\" class=\"feed-item pinned-item\">")
A("              <a-tag color=\"red\">置顶</a-tag>")
A("              <span class=\"pinned-title\">{{ post.title }}</span>")
A("              <span class=\"feed-meta\">{{ post.board_name }}</span>")
A("            </RouterLink>")
A("          </div>")
A("        </div>")
A("")
A("        <div class=\"feed-toolbar\">")
A("          <div class=\"feed-title\">")
A("            <h2>{{ route.params.slug ? '板块帖子' : '最新动态' }}</h2>")
A("            <span v-if=\"!loading\" class=\"feed-count\">{{ posts.length }} 条</span>")
A("          </div>")
A("        </div>")
A("")
A("        <a-spin :spinning=\"loading\">")
A("          <div class=\"feed-list pro-card\">")
A("            <RouterLink v-for=\"post in normalPosts\" :key=\"post.id\" :to=\"`/posts/${post.id}`\" class=\"feed-item\">")
A("              <div class=\"feed-item-top\">")
A("                <a-tag v-if=\"post.featured\" color=\"gold\">精华</a-tag>")
A("                <span class=\"feed-board\">{{ post.board_name }}</span>")
A("                <span class=\"feed-time\">{{ formatDate(post.created_at) }}</span>")
A("              </div>")
A("              <h3 class=\"feed-item-title\">{{ post.title }}</h3>")
A("              <p v-if=\"excerpt(post.content)\" class=\"feed-item-excerpt\">{{ excerpt(post.content) }}</p>")
A("              <div class=\"feed-item-bottom\">")
A("                <span class=\"user-inline-link\" @click.prevent.stop=\"router.push(`/users/${post.author_id}`)\">")
A("                  <a-avatar size=\"small\" :src=\"post.author_avatar || undefined\">{{ post.author_name.slice(0,1) }}</a-avatar>")
A("                  {{ post.author_name }}")
A("                  <VerifiedBadge :verified=\"post.author_verified\" :label=\"post.author_verification_label\" />")
A("                </span>")
A("                <span class=\"feed-meta\">{{ post.comment_count }} 评论</span>")
A("                <span class=\"feed-meta\">{{ post.views }} 浏览</span>")
A("              </div>")
A("            </RouterLink>")
A("            <a-empty v-if=\"!loading && !posts.length\" description=\"暂无内容\" :image=\"simpleEmpty\" class=\"feed-empty\" />")
A("          </div>")
A("        </a-spin>")
A("      </main>")
A("")
A("      <aside>")
A("        <div class=\"pro-card side-panel\">")
A("          <div class=\"card-header\"><h3>社区板块</h3><AppstoreOutlined /></div>")
A("          <RouterLink")
A("            v-for=\"board in boards\"")
A("            :key=\"board.id\"")
A("            :to=\"`/boards/${board.slug}`\"")
A("            class=\"board-card\"")
A("            :class=\"{ active: board.slug === route.params.slug }\"")
A("          >")
A("            <div class=\"board-icon\"><component :is=\"iconMap[board.icon] || MessageOutlined\" /></div>")
A("            <div class=\"board-info\"><b>{{ board.name }}</b><p>{{ board.description }}</p></div>")
A("            <span class=\"board-count\">{{ board.post_count }}</span>")
A("          </RouterLink>")
A("        </div>")
A("      </aside>")
A("    </div>")
A("")
A("    <a-drawer v-model:open=\"noticeOpen\" title=\"社区公告\" placement=\"right\" :width=\"360\">")
A("      <div v-if=\"!notices.length\" class=\"notice-empty\">暂无公告</div>")
A("      <div v-for=\"item in notices\" :key=\"item.id\" class=\"notice-item\">")
A("        <div class=\"notice-head\">")
A("          <a-tag v-if=\"item.pinned\" color=\"red\">置顶</a-tag>")
A("          <a-tag>{{ item.level || 'info' }}</a-tag>")
A("          <b>{{ item.title }}</b>")
A("        </div>")
A("        <p class=\"notice-body\">{{ item.content }}</p>")
A("        <div class=\"notice-time\">{{ formatDate(item.updated_at || item.created_at) }}</div>")
A("      </div>")
A("    </a-drawer>")
A("  </PageContainer>")
A("</template>")
A("")
A("<style scoped>")
A(".ad-banner-wrap { position: relative; margin-bottom: 16px; }")
A(".ad-banner { position: relative; display: block; width: 100%; aspect-ratio: 16 / 5; min-height: 120px; max-height: 220px; margin: 0; padding: 0; overflow: hidden; border: 1px solid var(--border); border-radius: var(--radius-lg); background: linear-gradient(120deg, #f0f5ff, #fff); box-shadow: var(--shadow-card); cursor: pointer; text-align: left; }")
A(".ad-banner:hover { border-color: #91caff; box-shadow: var(--shadow-2); }")
A(".ad-banner-img { width: 100%; height: 100%; object-fit: cover; display: block; }")
A(".ad-banner-fallback, .empty-banner { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 8px; width: 100%; height: 100%; color: var(--text-1); font-size: 16px; }")
A(".ad-hint { color: var(--text-3); font-size: 13px; }")
A(".ad-badge { position: absolute; top: 10px; left: 10px; z-index: 1; padding: 0 8px; border-radius: 2px; background: rgba(0,0,0,.5); color: #fff; font-size: 11px; line-height: 20px; }")
A(".ad-badge.on-image { background: rgba(0,0,0,.45); }")
A(".ad-dots { position: absolute; left: 0; right: 0; bottom: 10px; display: flex; justify-content: center; gap: 6px; pointer-events: none; }")
A(".ad-dot { pointer-events: auto; width: 8px; height: 8px; border: 0; border-radius: 50%; background: rgba(255,255,255,.55); box-shadow: 0 0 0 1px rgba(0,0,0,.12); cursor: pointer; padding: 0; }")
A(".ad-dot.active { background: var(--primary); width: 18px; border-radius: 8px; }")
A(".search-section { margin-bottom: 16px; }")
A(".search-icon { color: var(--text-3); }")
A(".feed-toolbar { display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; }")
A(".feed-title { display: flex; align-items: baseline; gap: 10px; }")
A(".feed-title h2 { margin: 0; color: var(--text-1); font-size: 16px; font-weight: 500; }")
A(".feed-count { color: var(--text-3); font-size: 13px; }")
A(".feed-list { padding: 0; overflow: hidden; }")
A(".feed-item { display: block; padding: 16px 20px; color: inherit; border-bottom: 1px solid var(--border); transition: background var(--motion-fast); }")
A(".feed-item:last-child { border-bottom: 0; }")
A(".feed-item:hover { background: #fafafa; color: inherit; }")
A(".feed-item-top { display: flex; align-items: center; flex-wrap: wrap; gap: 8px; margin-bottom: 6px; }")
A(".feed-board, .feed-time, .feed-meta { color: var(--text-3); font-size: 12px; }")
A(".feed-item-title { margin: 0 0 6px; color: var(--text-1); font-size: 16px; font-weight: 500; line-height: 1.4; }")
A(".feed-item:hover .feed-item-title { color: var(--primary); }")
A(".feed-item-excerpt { display: -webkit-box; margin: 0 0 10px; overflow: hidden; color: var(--text-2); font-size: 13px; line-height: 1.65; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }")
A(".feed-item-bottom { display: flex; align-items: center; flex-wrap: wrap; gap: 12px; }")
A(".feed-empty { padding: 48px 16px; }")
A(".pinned-block { margin-bottom: 16px; }")
A(".pinned-list .pinned-item { display: flex; align-items: center; gap: 10px; padding: 12px 16px; }")
A(".pinned-title { flex: 1; min-width: 0; overflow: hidden; color: var(--text-1); font-weight: 500; text-overflow: ellipsis; white-space: nowrap; }")
A(".side-panel { padding: 16px; }")
A(".card-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px; color: var(--text-2); }")
A(".card-header h3 { margin: 0; color: var(--text-1); font-size: 15px; font-weight: 500; }")
A(".board-card.active { color: var(--primary); background: var(--primary-bg); }")
A(".notice-item { padding: 12px 0; border-bottom: 1px solid var(--border); }")
A(".notice-head { display: flex; align-items: center; flex-wrap: wrap; gap: 6px; margin-bottom: 6px; }")
A(".notice-body { margin: 0; color: var(--text-2); white-space: pre-wrap; line-height: 1.7; font-size: 13px; }")
A(".notice-time { margin-top: 6px; color: var(--text-3); font-size: 12px; }")
A(".notice-empty { color: var(--text-3); text-align: center; padding: 40px 0; }")
A("@media (max-width: 991px) { .ad-banner { aspect-ratio: 16 / 7; max-height: 180px; } }")
A("@media (max-width: 560px) { .ad-banner { aspect-ratio: 2 / 1; min-height: 100px; max-height: 160px; } .feed-item { padding: 14px; } }")
A("</style>")
Path("frontend/src/views/HomeView.vue").write_text(chr(10).join(lines) + chr(10), encoding="utf-8")
print("wrote", Path("frontend/src/views/HomeView.vue").stat().st_size)
