<script setup lang="ts">
import { computed, type Component } from 'vue'
import {
  ArrowLeft,
  ArrowRight,
  Award,
  AtSign,
  BadgeCheck,
  Ban,
  Bell,
  Bookmark,
  BookOpen,
  CalendarDays,
  Check,
  ChevronRight,
  ClipboardCheck,
  CircleCheck,
  CircleDollarSign,
  CircleEllipsis,
  CirclePlus,
  CircleUserRound,
  Compass,
  Crown,
  CreditCard,
  Download,
  Eye,
  FileImage,
  FileText,
  Flag,
  Flame,
  HandCoins,
  Heart,
  House,
  Image,
  Info,
  KeyRound,
  Landmark,
  Link2,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Megaphone,
  MessageCircle,
  Moon,
  PackageOpen,
  PenLine,
  Plus,
  Quote,
  Repeat2,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  SquarePen,
  Star,
  Sun,
  Tag,
  Ticket,
  Trash2,
  TriangleAlert,
  Upload,
  Video,
  Volume2,
  VolumeX,
  UserRoundPlus,
  UsersRound,
  WalletCards,
  X,
} from '@lucide/vue'

const props = withDefaults(defineProps<{ name: string; size?: string | number; color?: string; strokeWidth?: number }>(), { size: 20, color: 'currentColor', strokeWidth: 1.9 })

const icons: Record<string, Component> = {
  add: Plus,
  award: Award,
  announcement: Megaphone,
  arrow: ArrowRight,
  back: ArrowLeft,
  badge: BadgeCheck,
  calendar: CalendarDays,
  category: Compass,
  crown: Crown,
  check: BadgeCheck,
  close: X,
  code: Ticket,
  credit: CreditCard,
  delete: Trash2,
  download: Download,
  document: FileText,
  edit: SquarePen,
  eye: Eye,
  file: FileText,
  flag: Flag,
  flame: Flame,
  github: CircleEllipsis,
  heart: Heart,
  home: House,
  image: Image,
  info: Info,
  invite: UserRoundPlus,
  link: Link2,
  lock: LockKeyhole,
  logout: LogOut,
  menu: Menu,
  message: MessageCircle,
  moon: Moon,
  more: CircleEllipsis,
  members: UsersRound,
  notice: Bell,
  people: UsersRound,
  payout: HandCoins,
  repost: Repeat2,
  review: ClipboardCheck,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: ShieldCheck,
  shop: PackageOpen,
  star: Bookmark,
  sun: Sun,
  success: CircleCheck,
  tag: Tag,
  topup: CirclePlus,
  upload: Upload,
  video: Video,
  user: CircleUserRound,
  wallet: WalletCards,
  warning: TriangleAlert,
  block: Ban,
  mail: Mail,
  mention: AtSign,
  bank: Landmark,
  balance: CircleDollarSign,
  chevron: ChevronRight,
  photo: FileImage,
  quote: Quote,
  pen: PenLine,
  plainCheck: Check,
  soundOn: Volume2,
  soundOff: VolumeX,
}

const component = computed<Component>(() => icons[props.name] || CircleEllipsis)
</script>

<template>
  <component :is="component" :size="props.size" :color="props.color" :stroke-width="props.strokeWidth" aria-hidden="true" />
</template>
