<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api, type PointProduct, type ShippingAddress } from '@/api'

const products = ref<PointProduct[]>([])
const busy = ref(0)
const addressProduct = ref<PointProduct | null>(null)
const notice = ref('')
const address = reactive<ShippingAddress>({ name: '', phone: '', province: '', city: '', district: '', detail: '' })
async function load() { products.value = (await api.get('/points/products')).data.data }
function beginRedeem(product: PointProduct) { if (product.physical) { addressProduct.value = product; return }; void redeem(product) }
async function redeem(product: PointProduct) { busy.value = product.id; notice.value = ''; try { await api.post(`/points/products/${product.id}/redeem`, { address: product.physical ? address : undefined }); notice.value = '兑换成功'; addressProduct.value = null; await load() } catch (error: any) { notice.value = error?.response?.data?.error?.message || '兑换失败' } finally { busy.value = 0 } }
onMounted(load)
</script>
<template><section class="rf-page store-page"><header class="rf-page-header"><div class="rf-page-heading"><h1>积分商城</h1><p>用积分兑换社区精选权益与周边。</p></div></header><p v-if="notice" class="store-notice" role="status">{{ notice }}</p><div class="store-grid"><article v-for="product in products" :key="product.id" class="store-item"><div class="store-image"><img v-if="product.image_url" :src="product.image_url" :alt="product.name"><span v-else>积分</span></div><div class="store-copy"><h2>{{ product.name }}</h2><p>{{ product.description }}</p><div class="store-meta"><strong>{{ product.points_required + product.shipping_points }} 积分</strong><span>{{ product.stock > 0 ? `库存 ${product.stock}` : '已售罄' }}</span></div><button class="rf-primary-button" :disabled="product.stock < 1 || busy === product.id" @click="beginRedeem(product)">{{ busy === product.id ? '兑换中…' : '立即兑换' }}</button></div></article><nut-empty v-if="!products.length" description="商城暂未上架商品" /></div><div v-if="addressProduct" class="address-overlay" @click.self="addressProduct=null"><form class="address-panel" @submit.prevent="redeem(addressProduct)"><header><div><h2>填写收货地址</h2><p>{{ addressProduct.name }}</p></div><button type="button" aria-label="关闭" @click="addressProduct=null">×</button></header><div class="address-grid"><label><span>收货人</span><input v-model.trim="address.name" required maxlength="80"></label><label><span>手机号</span><input v-model.trim="address.phone" required inputmode="tel" maxlength="32"></label><label><span>省份</span><input v-model.trim="address.province" required maxlength="50"></label><label><span>城市</span><input v-model.trim="address.city" required maxlength="50"></label><label><span>区县</span><input v-model.trim="address.district" maxlength="50"></label><label class="full"><span>详细地址</span><textarea v-model.trim="address.detail" required maxlength="200" rows="3" /></label></div><button class="rf-primary-button" type="submit" :disabled="busy === addressProduct.id">确认兑换</button></form></div></section></template>
<style scoped>.store-page{padding-bottom:48px}.store-notice{margin:0;padding:12px 20px;color:var(--primary);background:color-mix(in srgb,var(--primary) 9%,var(--rf-bg));font-size:13px}.store-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:var(--rf-line)}.store-item{display:flex;min-width:0;flex-direction:column;background:var(--rf-bg)}.store-image{display:grid;aspect-ratio:1.35;place-items:center;background:var(--rf-bg-subtle);color:var(--primary);font-size:32px;font-weight:800}.store-image img{width:100%;height:100%;object-fit:cover}.store-copy{display:flex;flex:1;flex-direction:column;gap:8px;padding:16px}.store-copy h2{margin:0;font-size:17px}.store-copy p{min-height:38px;margin:0;color:var(--rf-muted);font-size:13px;line-height:1.5}.store-meta{display:flex;align-items:center;justify-content:space-between;margin-top:auto}.store-meta strong{color:var(--primary)}.store-meta span{color:var(--rf-muted);font-size:12px}.store-copy button{width:100%;margin-top:8px}.address-overlay{position:fixed;z-index:2000;inset:0;display:grid;place-items:center;padding:20px;background:rgba(0,0,0,.48)}.address-panel{width:min(520px,100%);padding:20px;border-radius:8px;background:var(--rf-bg);box-shadow:0 24px 80px rgba(0,0,0,.24)}.address-panel header{display:flex;justify-content:space-between;align-items:flex-start}.address-panel h2{margin:0;font-size:20px}.address-panel p{margin:4px 0 0;color:var(--rf-muted);font-size:13px}.address-panel header button{width:40px;height:40px;border-radius:50%;color:var(--rf-muted);background:transparent;font-size:28px}.address-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.address-grid label{display:flex;flex-direction:column;gap:6px;color:var(--rf-muted);font-size:12px}.address-grid .full{grid-column:1/-1}.address-grid input,.address-grid textarea{width:100%;padding:10px;border:1px solid var(--rf-line);border-radius:6px;color:var(--rf-text);background:var(--rf-bg)}.address-panel>.rf-primary-button{width:100%}@media(max-width:640px){.store-grid,.address-grid{grid-template-columns:1fr}.address-grid .full{grid-column:auto}}</style>
