<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { errorMessage, fetchSiteSettings, sendRegistrationVerification, type SiteSettings } from '@/api'
import { useAuthStore } from '@/stores/auth'
import HumanVerification from '@/components/HumanVerification.vue'
import AppIcon from '@/components/AppIcon.vue'
import { Notify } from '@nutui/nutui'

const auth = useAuthStore(); const router = useRouter(); const verification = ref<InstanceType<typeof HumanVerification> | null>(null); const site = ref<SiteSettings | null>(null)
const name = ref(''); const email = ref(''); const password = ref(''); const confirm = ref(''); const emailCode = ref(''); const captchaToken = ref(''); const captchaRequired = ref(false); const cooldown = ref(0); const loading = ref(false); const sending = ref(false); let timer: number | undefined
onMounted(async () => { site.value = await fetchSiteSettings().catch(() => null) }); onBeforeUnmount(() => { if (timer) window.clearInterval(timer) })
async function sendCode() { if (captchaRequired.value && !captchaToken.value) { Notify.warn('请先完成人机验证'); return }; sending.value = true; try { const result = await sendRegistrationVerification(email.value, captchaToken.value); cooldown.value = Math.min(result.expires_in || 60, 600); timer = window.setInterval(() => { cooldown.value -= 1; if (cooldown.value <= 0 && timer) { window.clearInterval(timer); timer = undefined } }, 1000); verification.value?.reset() } catch (e) { Notify.danger(errorMessage(e, '验证码发送失败')); verification.value?.reset() } finally { sending.value = false } }
async function submit() { if (password.value !== confirm.value) { Notify.warn('两次密码不一致'); return }; if (site.value?.require_email_verification && !/^\d{6}$/.test(emailCode.value)) { Notify.warn('请输入 6 位邮箱验证码'); return }; if (captchaRequired.value && !captchaToken.value) { Notify.warn('请先完成人机验证'); return }; loading.value = true; try { await auth.register(email.value, password.value, name.value, captchaToken.value, emailCode.value); Notify.success('注册成功'); await router.push('/') } catch (e) { Notify.danger(errorMessage(e, '注册失败')); verification.value?.reset() } finally { loading.value = false } }
</script>

<template><div class="auth-page"><div class="auth-card"><div class="auth-heading"><h1>创建账号</h1><p>{{ site?.site_description || '加入中国 Roblox 玩家社区。' }}</p></div><form class="rf-auth-form" @submit.prevent="submit"><label>昵称<div class="rf-field"><AppIcon name="user" size="18" /><input v-model="name" maxlength="80" placeholder="社区中显示的名字" required /></div></label><label>邮箱<div class="rf-field"><AppIcon name="message" size="18" /><input v-model="email" type="email" autocomplete="email" placeholder="name@example.com" required /></div></label><label v-if="site?.require_email_verification">邮箱验证码<div class="rf-code-field"><input v-model="emailCode" maxlength="6" inputmode="numeric" placeholder="6 位验证码" /><button type="button" :disabled="cooldown > 0 || sending || (captchaRequired && !captchaToken)" @click="sendCode">{{ cooldown > 0 ? `${cooldown}s` : '发送验证码' }}</button></div></label><label>密码<div class="rf-field"><AppIcon name="settings" size="18" /><input v-model="password" type="password" autocomplete="new-password" placeholder="至少 10 个字符" required /></div></label><label>确认密码<div class="rf-field"><AppIcon name="settings" size="18" /><input v-model="confirm" type="password" autocomplete="new-password" placeholder="再次输入密码" required /></div></label><HumanVerification ref="verification" @token="captchaToken = $event" @required="captchaRequired = $event" /><button type="submit" class="rf-primary-button rf-auth-submit" :disabled="loading || (captchaRequired && !captchaToken)">{{ loading ? '注册中…' : '注册' }}</button></form><div class="auth-footer">已有账号？ <RouterLink to="/login">登录</RouterLink></div></div></div></template>
