<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Notify } from '@nutui/nutui'
import { createVerificationApplication, errorMessage, fetchMyVerificationApplications, type VerificationApplication } from '@/api'
import PageContainer from '@/components/PageContainer.vue'
import AppIcon from '@/components/AppIcon.vue'
const items = ref<VerificationApplication[]>([]); const loading = ref(true); const submitting = ref(false); const form = reactive({ verification_type: 'creator', requested_label: '', evidence_url: '', statement: '' })
async function load() { try { items.value = await fetchMyVerificationApplications() } catch (e) { Notify.danger(errorMessage(e, '认证申请加载失败')) } finally { loading.value = false } }
async function submit() { if (!form.requested_label.trim() || !form.evidence_url.trim() || form.statement.trim().length < 30) { Notify.warn('请完整填写认证资料，申请说明至少 30 个字'); return }; submitting.value = true; try { await createVerificationApplication({...form}); Notify.success('认证申请已提交，等待管理员审核'); Object.assign(form, { verification_type:'creator', requested_label:'', evidence_url:'', statement:'' }); await load() } catch (e) { Notify.danger(errorMessage(e, '认证申请提交失败')) } finally { submitting.value = false } }
const statusLabel = (v:string) => ({pending:'审核中',approved:'已通过',rejected:'已驳回'} as Record<string,string>)[v] || v; onMounted(load)
</script>
<template><PageContainer title="蓝微认证"><div class="rf-info-banner"><AppIcon name="check" size="18" /><span>认证不是付费服务。请提交可公开核验的证明链接，冒用身份或伪造材料会被驳回。</span></div><div class="rf-verification-grid"><form class="rf-panel rf-editor-form" @submit.prevent="submit"><label>认证类型<select v-model="form.verification_type"><option value="creator">创作者</option><option value="developer">开发者/工作室</option><option value="organization">组织/社群</option><option value="community">社区贡献者</option></select></label><label>希望显示的认证名称<input v-model="form.requested_label" maxlength="80" placeholder="例如：某某工作室 / 某某创作者" required /></label><label>证明材料链接<input v-model="form.evidence_url" type="url" placeholder="https://…" required /></label><label>申请说明<textarea v-model="form.statement" rows="8" maxlength="2000" placeholder="介绍你的身份、作品、社区贡献和材料关联，至少 30 个字。" required /></label><button type="submit" class="rf-primary-button" :disabled="submitting">{{ submitting ? '提交中…' : '提交认证申请' }}</button></form><aside><section class="rf-panel rf-guideline"><h2>审核标准</h2><ul><li>材料必须可以公开访问和核验</li><li>认证名称应与材料中的身份一致</li><li>通过后蓝标同步显示到帖子、评论、资源和主页</li></ul></section><section class="rf-panel"><div class="rf-section-label"><span>我的申请</span><small>{{ items.length }} 条</small></div><div v-if="loading" class="rf-loading-block">加载中…</div><div v-else-if="items.length" class="rf-application-list"><article v-for="item in items" :key="item.id"><strong>{{ item.requested_label }}</strong><span :class="`rf-status-${item.status}`">{{ statusLabel(item.status) }}</span><small>{{ new Date(item.created_at).toLocaleString('zh-CN') }}</small><p v-if="item.review_note">{{ item.review_note }}</p></article></div><div v-else class="rf-empty">还没有申请记录</div></section></aside></div></PageContainer></template>
